name: Playwright Tests test edition

on: 
  push:
    branches: [master]
  pull-requset:
    branches: [master]
  workflow_dispatch:

env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  playwright:
    name: "Playwright test"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root
  
