name: Playwright Tests test edition

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
  NEW_USER_PASSWORD: ${{ secrets.NEW_USER_PASSWORD }}
  BASE_URL: ${{ secrets.BASE_URL }}
  ECOMMERCE_URL: ${{ secrets.ECOMMERCE_URL }}
  ECOMMERCE_TEST_URL: ${{ secrets.ECOMMERCE_TEST_URL }}
  NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
  STG_BASE_URL: ${{ secrets.STG_BASE_URL }}
  CRM_API_URL: ${{ secrets.CRM_API_URL }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  
jobs:   
  playwright-test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.3-jammy
    strategy:
      # якщо буде тру - то при фейлі одної джоби інші будуть канселитись
      fail-fast: false
      # те на якому енві будемо ранити
      matrix:
        project: [chromium]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cacheStep
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run playwright tests
        run: npx playwright test api/cart --project=${{ matrix.project }}
      # create artifact for downloading
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.project }} report
          path: playwright-report/
      
  merge-reports:
    name: Merge Reports
    if: ${{ always() }}
    needs: [playwright-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: playwright-report/
      # Run Download Merge HTML dependency
      - name: Download Merge HTML
        run: npm install playwright-merge-html-reports --dev
      # Run HTML Report Merge
      - name: Run Report Merge
        run: node src/modules/utils/mergeReports.js
